-- ============================================================
-- Step 0: Prerequisites - Create Database, Schema, Roles, Warehouse
-- ============================================================
-- Run with: ACCOUNTADMIN or SECURITYADMIN
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MASKING_LAB_DB;
CREATE SCHEMA IF NOT EXISTS MASKING_LAB_DB.LAB_SCHEMA;

CREATE WAREHOUSE IF NOT EXISTS LAB_WAREHOUSE
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS LAB_ADMIN;
CREATE ROLE IF NOT EXISTS LAB_ANALYST;

GRANT USAGE ON WAREHOUSE LAB_WAREHOUSE TO ROLE LAB_ADMIN;
GRANT USAGE ON WAREHOUSE LAB_WAREHOUSE TO ROLE LAB_ANALYST;

GRANT OWNERSHIP ON DATABASE MASKING_LAB_DB TO ROLE LAB_ADMIN;
GRANT OWNERSHIP ON SCHEMA MASKING_LAB_DB.LAB_SCHEMA TO ROLE LAB_ADMIN;

GRANT CREATE MASKING POLICY ON SCHEMA MASKING_LAB_DB.LAB_SCHEMA TO ROLE LAB_ADMIN;
GRANT CREATE TAG ON SCHEMA MASKING_LAB_DB.LAB_SCHEMA TO ROLE LAB_ADMIN;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE LAB_ADMIN;
GRANT APPLY TAG ON ACCOUNT TO ROLE LAB_ADMIN;

GRANT ROLE LAB_ADMIN TO USER NATARAJPL;
GRANT ROLE LAB_ANALYST TO USER NATARAJPL;
