-- ============================================================
-- FILE: 01_setup_roles_and_db.sql
-- PURPOSE: Setup roles, warehouse, database, and schema
-- ============================================================

USE ROLE SYSADMIN; -- Sysadmin role to be used to create Warehouse, Database & Schemas.

-- Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS RAP_WH --RAP stands for Row Access Policy
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create Database & Schema
CREATE DATABASE IF NOT EXISTS HOSPITALITY_DB;
CREATE SCHEMA IF NOT EXISTS HOSPITALITY_DB.FINANCE;

-- ============================================================
-- Create Roles
-- ============================================================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_REGION_APAC;
CREATE ROLE IF NOT EXISTS ROLE_REGION_EMEA;
CREATE ROLE IF NOT EXISTS ROLE_REGION_AMER;
CREATE ROLE IF NOT EXISTS ROLE_FINANCE_ADMIN;

-- Grant usage
GRANT USAGE ON WAREHOUSE RAP_WH         TO ROLE ROLE_REGION_APAC;
GRANT USAGE ON WAREHOUSE RAP_WH         TO ROLE ROLE_REGION_EMEA;
GRANT USAGE ON WAREHOUSE RAP_WH         TO ROLE ROLE_REGION_AMER;
GRANT USAGE ON WAREHOUSE RAP_WH         TO ROLE ROLE_FINANCE_ADMIN;

GRANT USAGE ON DATABASE HOSPITALITY_DB  TO ROLE ROLE_REGION_APAC;
GRANT USAGE ON DATABASE HOSPITALITY_DB  TO ROLE ROLE_REGION_EMEA;
GRANT USAGE ON DATABASE HOSPITALITY_DB  TO ROLE ROLE_REGION_AMER;
GRANT USAGE ON DATABASE HOSPITALITY_DB  TO ROLE ROLE_FINANCE_ADMIN;

GRANT USAGE ON SCHEMA HOSPITALITY_DB.FINANCE TO ROLE ROLE_REGION_APAC;
GRANT USAGE ON SCHEMA HOSPITALITY_DB.FINANCE TO ROLE ROLE_REGION_EMEA;
GRANT USAGE ON SCHEMA HOSPITALITY_DB.FINANCE TO ROLE ROLE_REGION_AMER;
GRANT USAGE ON SCHEMA HOSPITALITY_DB.FINANCE TO ROLE ROLE_FINANCE_ADMIN;

-- Assign roles to users (replace with actual usernames)
GRANT ROLE ROLE_REGION_APAC   TO USER APAC_USER;
GRANT ROLE ROLE_REGION_EMEA   TO USER EMEA_USER;
GRANT ROLE ROLE_REGION_AMER   TO USER AMER_USER;
GRANT ROLE ROLE_FINANCE_ADMIN TO USER ADMIN_USER;
